[package]
name = "binichonline"
version = "0.2.0"
authors = ["Sebastian Schulze <github.com@bascht.com>"]

[dependencies]
time = "0.1.38"
curl = "0.4.8"
term = "0.4.6"
url = "1.5.1"

[[bin]]
name = "binichonline"
doc = false
